### ISSUE TITLE
EBS: UI changes for onboarding simplification (checklist)  aka new UI defaults

### ISSUE THREAD

**Issue by chadfurman** [CoSMoSoftware/OBS-studio-webrtc#107]
- [x] Remove “enable advanced encoder settings” checkbox option
   - https://www.screencast.com/t/CiptdHDsG
- [x] Remove ‘output mode.’ It should always be in simple mode.
   - https://www.screencast.com/t/JpcyzCF9R9
- [x] Set default FPS in settings to 60
  - https://www.screencast.com/t/9N2zeWqG
- [x] Set default audio bitrate to 320 and 4000 for video bitrate 
   - https://www.screencast.com/t/UylEzMrQ1
- [x] Remove “Use Buffering” option under video capture device settings. 
   - https://www.screencast.com/t/4QjxAY8Vx5Ja
- [x] Set “transform” default to fit to screen when a video capture device or display capture source is selected.
   - https://drive.google.com/file/d/16pNMN5ozXokRgiOPK1gFhFs98PDnJ11r/view?usp=sharing. 
- [x] In settings / audio, set all audio devices to disabled by default.
   - https://www.screencast.com/t/H9FqFN52MNZ
- [x] Remove the red “manual bandwidth” notice at the top of the stream tab page.
   - https://gyazo.com/c564eefb824ca659a5482dd950163395
- [x] Set downscale filter to “Bilinear” by default.
   - https://gyazo.com/ec595a3de063df4358e668a8931691fe

**Comment by agouaillard-cosmo** [comment]
basics: one ticket, one task .... Will dispatch.

**Comment by agouaillard-cosmo** [comment]
all dispatched.
